/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testtwolib_MainActivity */

#ifndef _Included_com_rect_dymanic_MainActivity
#define _Included_com_rect_dymanic_MainActivity
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_rect_dymanic_MainActivity_CallDymanicFuncFormHTTP
  (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
